### ISSUE TITLE
Add desktop dependencies automatically

### ISSUE THREAD

**Issue by Boomaa23** [Team5818/GradleRIO-Redux#1]
There's a gradle task `simulateJava` (a simulation tool) included in GradleRIO, which requires desktop dependencies to be added from WPILib. These are all the dependencies contained within `wpi.deps.wpilibJni(...)` and `wpi.deps.vendor.jni(...)`. Additionally, the `halsim_gui` dependency must be added to the `simulation config, given some inputs. The platform is retrieved using reflection. Working code for this is as listed below.
```kotlin
val platform = wpi.platforms.javaClass.getDeclaredField("desktop").get(null) as String

dependencies {
    for (depJni: String in (wpi.deps.wpilibJni(platform) + wpi.deps.vendor.jni(platform))) {
        nativeDesktopZip(depJni)
    }
    simulation("edu.wpi.first.halsim:halsim_gui:${wpi.wpilibVersion}:$platform@zip")
}
```
Additionally, Windows for some reason doesn't open the generated batch file ( `/build/gradlerio_simulateJava.bat`), instead choosing to open a blank command prompt. As a workaround, the below code opens the script in a new command prompt window, as intended (though only on windows computers where it is an issue). 
```kotlin
tasks.register("windowsLaunchSim") {
    doLast {
        project.exec{
            workingDir = file("./build/")
            commandLine("cmd", "/C", "start", "gradlerio_simulateJava.bat")
        }
    }
}
if (platform.contains("windows")) {
    tasks.getByName("simulateJava").finalizedBy(tasks.getByName("windowsLaunchSim"))
}
```
This issue is to request that these desktop dependencies be included automatically, and perhaps implement a better solution for the Windows-specific issue.

**Comment by Boomaa23** [comment]
I suppose this is a better way to detect a Windows computer
```kotlin
if (org.gradle.internal.os.OperatingSystem.current().isWindows) {
    tasks.getByName("simulateJava").finalizedBy(tasks.getByName("windowsLaunchSim"))
}
```

**Comment by octylFractal** [comment]
no internal api plz thanks

**Comment by octylFractal** [comment]
With 6df23eb9e7e56c2232f71815f7514c77882c9d63 this appears to be working without the hack. Please report back if the GUI doesn't open, as I am unable to test that (vm feels bad man). I do get a GUI error, so I think it should start without issue.
